package fr.formation.students.enumeration;

public class StringApplication {

    public static void main(String[] args) {
        String a = "a";
        String b = "b";

        //Toujours faire appel à equals pour une comparaison d'objet et non "=="
        System.out.println(a.equals(b));
        String[] words = LOREM.split(" ");
        concat(words);
        stringBuilder(words);

    }

    private static void stringBuilder(String[] words) {
        long start = System.currentTimeMillis();
        StringBuilder result = new StringBuilder();
        for (String word : words) {
            result.append(word);
            result.append("");
        }
        long end = System.currentTimeMillis();
        System.out.println("StringBuilder took " + (end - start) + " ms");
        System.out.println(result);
    }
        private static void concat (String[]words){
            long start = System.currentTimeMillis();
            String result = null;
            for (String word : words) {
                result += word + "";
            }
            long end = System.currentTimeMillis();
            System.out.println("concat took " + (end - start) + " ms");
            System.out.println(result);
        }
        private final static String LOREM = "\n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. \n" +
                "\n" +
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dapibus vestibulum lorem ac vestibulum. Aenean id massa vel mi facilisis congue. Suspendisse potenti. Nunc rhoncus risus ac aliquet cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur eu enim elit. Quisque ac iaculis ante. Sed eu augue quis arcu consectetur condimentum placerat vel augue. Nulla quis faucibus dolor. Etiam ac pulvinar mi. Aenean id finibus purus, ac cursus urna. Sed lobortis mi a eros elementum, ac eleifend sapien iaculis. Praesent lorem justo, aliquet sit amet elit nec, lobortis sodales nunc. Nulla facilisi.\n" +
                "\n" +
                "Cras ac luctus augue. Praesent nibh neque, finibus nec semper sollicitudin, laoreet ac mauris. Vestibulum pulvinar, nunc id cursus ultricies, ipsum velit tempus tortor, non pellentesque erat sem ut purus. Proin et dolor tincidunt, vehicula purus a, cursus enim. Praesent scelerisque nisl massa, nec aliquam ex porttitor vitae. Aenean vitae fringilla risus. Nulla quis lorem felis. Fusce diam mi, suscipit sodales dignissim ac, mollis sit amet ligula. Mauris fermentum commodo risus, eget laoreet massa ultrices vel. Nam luctus finibus est, non lacinia erat facilisis eget. Fusce cursus augue eget orci dignissim, vitae rutrum ipsum blandit. Proin facilisis magna libero, a pellentesque metus efficitur at. Sed tempus porta efficitur. Pellentesque et nunc id urna efficitur tempor. Mauris et commodo diam. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
                "\n" +
                "Nullam finibus eget libero a malesuada. Sed eu consectetur nisi. In at aliquet elit. Vestibulum pharetra sed erat vitae gravida. Donec tempus a nisi at euismod. Phasellus ut purus lacinia, condimentum magna eu, ullamcorper mauris. Nunc iaculis neque non commodo posuere. Sed nec fermentum diam. Curabitur sed dui non nibh rutrum ultrices non nec est. Aenean a scelerisque ante, at varius arcu. Proin venenatis nec justo ut congue. Nulla facilisi. Donec rutrum elit at turpis lacinia, ut cursus felis consequat.\n" +
                "\n" +
                "Fusce id molestie velit, at congue eros. Sed at sollicitudin nisi. Morbi purus massa, tincidunt commodo enim id, blandit dapibus quam. Maecenas in nunc orci. Mauris tincidunt massa odio, ut ornare enim luctus in. Curabitur condimentum varius lacus vel suscipit. Quisque diam ante, congue ac nibh non, imperdiet rutrum nunc. Vivamus justo diam, condimentum a felis nec, ultrices semper sem. Nam in pellentesque enim. Nunc dictum congue magna, ut luctus ipsum placerat imperdiet. Nulla luctus, lacus non lobortis cursus, leo purus fermentum eros, a posuere nunc augue eu felis. Nulla non arcu vitae lectus efficitur tincidunt vitae quis justo. Nam at accumsan risus, quis iaculis metus.\n" +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. " +
                "\n" +
                "Mauris at mi tortor. Curabitur et eleifend tortor. Donec sit amet ligula porta, luctus ligula sit amet, vulputate lorem. Nullam porttitor ut ligula vel tempus. Nullam pulvinar erat sit amet eros laoreet placerat. Duis tempus, dolor quis ullamcorper ornare, magna diam blandit eros, in consequat odio odio in ex. Fusce a ligula nisi. In vel tincidunt nisi, at vulputate sapien. ";

    }

